services:
    web:
        build:
            context: ./vendor/versyx/framework/docker
            dockerfile: Dockerfile
        container_name: versyx-web
        ports:
            - ${HTTP_LOCAL_PORT:-80}:${HTTP_CONTAINER_PORT:-80}
        volumes:
            - ./vendor/versyx/framework/docker/vhosts:/etc/apache2/sites-enabled
            - .:/var/www/html
        environment:
            - APP_ENV=${APP_ENV}
            - APP_ROOT=${APP_ROOT}
            - APP_NAME=${APP_NAME}
            - APP_DEBUG=${APP_DEBUG}
            - APP_CACHE=${APP_CACHE}
        networks:
            - versyx

networks:
    versyx:
        driver: bridge