services:
    web:
        build:
            context: ./vendor/versyx/framework/docker
            dockerfile: Dockerfile
        container_name: versyx-web
        ports:
            - ${HTTP_LOCAL_PORT:-80}:${HTTP_CONTAINER_PORT:-80}
        volumes:
            - ./vendor/versyx/framework/docker/vhosts:/etc/apache2/sites-enabled
            - .:/var/www/html
        env_file: .env
        networks:
            - versyx
    database:
        image: mariadb:latest
        container_name: versyx-db
        ports:
            - ${DATABASE_LOCAL_PORT:-3306}:${DATABASE_CONTAINER_PORT:-3306}
        environment:
            - MYSQL_USER=${DB_USERNAME:-versyx}
            - MYSQL_PASSWORD=${DB_PASSWORD:-password}
            - MYSQL_DATABASE=${DB_DATABASE:-versyx}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
        networks:
            - versyx

networks:
    versyx:
        driver: bridge